version: '3.2'

services:
  local_projects:
    image: ${HMD_CONTAINER_REGISTRY}/hmd-ms-local-projects:${HMD_MS_LOCAL_PROJECTS_VERSION}
    container_name: hmd_ms_local_projects
    environment:
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_XRAY_SDK_ENABLED: 'false'
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
      DD_FLUSH_TO_LOG: 'true'
      DD_LAMBDA_HANDLER: 'main.handler'
      DD_TRACE_ENABLED: 'true'
      GIT_AUTHOR_NAME: ${HMD_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL: ${HMD_AUTHOR_EMAIL}
      GIT_COMMITTER_NAME: ${HMD_AUTHOR_NAME}
      GIT_COMMITTER_EMAIL: ${HMD_AUTHOR_EMAIL}
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DB_ENGINES: '{}'
      HMD_DID: ${HMD_DID}
      HMD_ENTITY_CONFIG: '{"__default__": {"persistence": [], "create": {"exposed": false}, "read": {"exposed": false}, "update": {"exposed": false}, "delete": {"exposed": false}, "search": {"exposed": false}}}'
      HMD_ENVIRONMENT: local
      HMD_HOSTNAME: ${HMD_HOSTNAME}
      HMD_INSTANCE_NAME: ms-local-projects
      HMD_NAMING_SERVICE: ${HMD_NAMING_SERVICE}
      HMD_PROJECTS_DIR: '/projects'
      HMD_REGION: ${HMD_REGION}
      HMD_REPO_NAME: hmd-ms-local-projects
      HMD_REPO_VERSION: ${HMD_MS_LOCAL_PROJECTS_VERSION}
      OPERATIONS_MODULE: hmd_ms_local_projects.hmd_ms_local_projects
      SCHEMA_URI: '/schemas/hmd-lang-projects'
    expose:
      - 8080
    volumes:
      - type: bind
        source: ${HMD_HOME}/studio/projects
        target: /projects
      - type: bind
        source: ~/.aws
        target: /root/.aws
