version: "3.2"

services:
  datadog:
    container_name: datadog
    image: datadog/agent:latest
    expose:
      - 5555
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_HOSTNAME=${HMD_HOSTNAME}
      - DD_HEALTH_PORT=5555
      - DD_ENV=local
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true
      - DD_CONTAINER_EXCLUDE=name:datadog
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - 'DD_DOCKER_LABELS_AS_TAGS={"io.hmdlabs.service": "service", "io.hmdlabs.environment": "env", "io.hmdlabs.version": "version"}'
      - 'DD_DOCKER_ENV_AS_TAGS={"HMD_REPO_HOME": "repo_name", "HMD_INSTANCE_NAME": "instance_name", "HMD_CUSTOMER_CODE": "customer_code"}'
      - HMD_CUSTOMER_CODE=${HMD_CUSTOMER_CODE}
      - HMD_DID=${HMD_DID}
      - HMD_ENVIRONMENT=${HMD_ENVIRONMENT}
      - HMD_REGION=${HMD_REGION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  proxy:
    container_name: hmd_proxy
    image: ${HMD_CONTAINER_REGISTRY}/hmd-img-local-gateway:0.1.15
    environment:
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DID: ${HMD_DID}
      HMD_ENVIRONMENT: ${HMD_ENVIRONMENT}
      HMD_REGION: ${HMD_REGION}
    ports:
      - "80:80"

  db:
    container_name: hmd_db
    environment:
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DID: ${HMD_DID}
      HMD_ENVIRONMENT: ${HMD_ENVIRONMENT}
      HMD_REGION: ${HMD_REGION}
    image: ${HMD_CONTAINER_REGISTRY}/hmd-postgres-base:0.1.5
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ${HMD_HOME}/postgresql/data
        target: /var/lib/postgresql/data

  local_projects:
    image: ${HMD_CONTAINER_REGISTRY}/hmd-ms-local-projects:0.1.18
    container_name: hmd_ms_local_projects
    environment:
      HMD_INSTANCE_NAME: ms-local-projects
      HMD_REPO_NAME: hmd-ms-local-projects
      HMD_REPO_VERSION: "0.1.18"
      HMD_ENVIRONMENT: ${HMD_ENVIRONMENT}
      HMD_REGION: ${HMD_REGION}
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DID: ${HMD_DID}
      HMD_DB_ENGINES: "{}"
      HMD_ENTITY_CONFIG: '{"__default__": {"persistence": [], "create": {"exposed": false}, "read": {"exposed": false}, "update": {"exposed": false}, "delete": {"exposed": false}, "search": {"exposed": false}}}'
      HMD_PROJECTS_DIR: "/projects"
      HMD_NAMING_SERVICE: ${HMD_NAMING_SERVICE}
      HMD_NAMING_API_KEY: ${HMD_NAMING_API_KEY}
      HMD_PROJECTS_API_KEY: ${HMD_PROJECTS_ADMIN_API_KEY}
      SCHEMA_URI: "/schemas/hmd-lang-projects"
      OPERATIONS_MODULE: hmd_ms_local_projects.hmd_ms_local_projects
      AWS_PROFILE: ${AWS_PROFILE}
      DD_LAMBDA_HANDLER: "main.handler"
      DD_TRACE_ENABLED: "true"
      DD_FLUSH_TO_LOG: "true"
    expose:
      - 8080
    volumes:
      - type: bind
        source: ${HMD_HOME}/studio/projects
        target: /projects
      - type: bind
        source: ~/.aws
        target: /root/.aws
