version: "3.2"

services:
  datadog:
    container_name: datadog
    image: datadog/agent:latest
    expose:
      - 5555
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_HOSTNAME=${HMD_HOSTNAME}
      - DD_HEALTH_PORT=5555
      - DD_ENV=local
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true
      - DD_CONTAINER_EXCLUDE=name:datadog
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - 'DD_DOCKER_LABELS_AS_TAGS={"io.hmdlabs.service": "service", "io.hmdlabs.environment": "env", "io.hmdlabs.version": "version"}'
      - 'DD_DOCKER_ENV_AS_TAGS={"HMD_REPO_HOME": "repo_name", "HMD_INSTANCE_NAME": "instance_name", "HMD_CUSTOMER_CODE": "customer_code"}'
      - HMD_CUSTOMER_CODE=${HMD_CUSTOMER_CODE}
      - HMD_DID=${HMD_DID}
      - HMD_ENVIRONMENT=local
      - HMD_REGION=${HMD_REGION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - datadog_s6:/var/run/s6
      - datadog_log:/var/log/datadog

  proxy:
    container_name: hmd_proxy
    image: ${HMD_CONTAINER_REGISTRY}/hmd-img-local-gateway:${HMD_IMG_LOCAL_GATEWAY_VERSION}
    environment:
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DID: ${HMD_DID}
      HMD_ENVIRONMENT: local
      HMD_HOME: ${HMD_HOME}
      HMD_REGION: ${HMD_REGION}
    ports:
      - "80:80"

  db:
    container_name: hmd_db
    environment:
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DID: ${HMD_DID}
      HMD_ENVIRONMENT: local
      HMD_REGION: ${HMD_REGION}
    image: ${HMD_CONTAINER_REGISTRY}/hmd-postgres-base:${HMD_POSTGRES_BASE_VERSION}
    ports:
      - "5432:5432"
    entrypoint: /postgres-scripts/docker-entrypoint.sh
    command: postgres
    volumes:
      - type: bind
        source: ${HMD_HOME}/postgresql/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres-scripts/
        target: /postgres-scripts/

  local_projects:
    image: ${HMD_CONTAINER_REGISTRY}/hmd-ms-local-projects:${HMD_MS_LOCAL_PROJECTS_VERSION}
    container_name: hmd_ms_local_projects
    environment:
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_XRAY_SDK_ENABLED: "false"
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
      DD_FLUSH_TO_LOG: "true"
      DD_LAMBDA_HANDLER: "main.handler"
      DD_TRACE_ENABLED: "true"
      HMD_CUSTOMER_CODE: ${HMD_CUSTOMER_CODE}
      HMD_DB_ENGINES: "{}"
      HMD_DID: ${HMD_DID}
      HMD_ENTITY_CONFIG: '{"__default__": {"persistence": [], "create": {"exposed": false}, "read": {"exposed": false}, "update": {"exposed": false}, "delete": {"exposed": false}, "search": {"exposed": false}}}'
      HMD_ENVIRONMENT: local
      HMD_HOSTNAME: ${HMD_HOSTNAME}
      HMD_INSTANCE_NAME: ms-local-projects
      HMD_NAMING_API_KEY: ${HMD_NAMING_API_KEY}
      HMD_NAMING_SERVICE: ${HMD_NAMING_SERVICE}
      HMD_PROJECTS_API_KEY: ${HMD_PROJECTS_ADMIN_API_KEY}
      HMD_PROJECTS_DIR: "/projects"
      HMD_REGION: ${HMD_REGION}
      HMD_REPO_NAME: hmd-ms-local-projects
      HMD_REPO_VERSION: ${HMD_MS_LOCAL_PROJECTS_VERSION}
      OPERATIONS_MODULE: hmd_ms_local_projects.hmd_ms_local_projects
      SCHEMA_URI: "/schemas/hmd-lang-projects"
    expose:
      - 8080
    volumes:
      - type: bind
        source: ${HMD_HOME}/studio/projects
        target: /projects
      - type: bind
        source: ~/.aws
        target: /root/.aws

volumes:
  datadog_s6:
    name: neuronsphere_${HMD_CUSTOMER_CODE}_datadog_s6
  datadog_log:
    name: neuronsphere_${HMD_CUSTOMER_CODE}_datadog_log
