package lock

import (
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/neuronsphere/hmd-cli-neuronsphere/internal/librarian"
	"github.com/neuronsphere/hmd-cli-neuronsphere/internal/localspec"
)

// want builds one declared want. The fields a lock reads are the only ones set.
func want(key, class, spec string, profiles, satisfies []string) localspec.Want {
	return localspec.Want{
		Key: key, RepoClassName: class, VersionSpec: spec,
		DefaultName: key, Profiles: profiles, Satisfies: satisfies,
	}
}

// pinned resolves every want to one version, which is what tiers one and two
// hand Build.
func pinned(versions map[string]string) func(localspec.Want) string {
	return func(w localspec.Want) string { return versions[w.RepoClassName] }
}

// The content path is generated by librarian.Spec and never by a second format
// string in this package. BACON's pre_build_artifacts grammar and the
// librarian's content paths are one vocabulary; a private copy is how they
// become two, and this repository has already paid for that once.
func TestContentPathComesFromTheLibrarianGrammar(t *testing.T) {
	t.Parallel()

	l, unresolved, err := Build("hmd-ms-myapi", "pins",
		[]localspec.Want{want("trino", "hmd-inf-trino", "0.3.12", nil, []string{"trino"})},
		pinned(map[string]string{"hmd-inf-trino": "0.3.12"}))
	if err != nil || len(unresolved) != 0 {
		t.Fatalf("Build: %v, unresolved %v", err, unresolved)
	}
	// Built by calling the grammar, not by writing the expected string out --
	// so this fails the day the two fork rather than agreeing with a stale copy.
	want := librarian.Spec{Name: "hmd-inf-trino", Version: "0.3.12", ItemType: "build"}.ContentPath()
	if got := l.Resolved[0].ContentPath; got != want {
		t.Errorf("content_path = %q, want %q", got, want)
	}
	if !strings.HasPrefix(want, "repository:/") {
		t.Fatalf("the fixture no longer exercises a content path: %q", want)
	}
}

func TestWriteReadRoundTrip(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	l, _, err := Build("hmd-ms-myapi", "env:dev", []localspec.Want{
		want("trino", "hmd-inf-trino", "~= 0.3", nil, []string{"trino"}),
		want("ms-transform", "hmd-ms-transform", "~= 0.5", []string{"transforms", "full"}, nil),
	}, pinned(map[string]string{"hmd-inf-trino": "0.3.12", "hmd-ms-transform": "0.5.201"}))
	if err != nil {
		t.Fatal(err)
	}
	if err := Write(dir, l); err != nil {
		t.Fatal(err)
	}

	raw, err := os.ReadFile(filepath.Join(dir, FileName))
	if err != nil {
		t.Fatal(err)
	}
	// SPEC002 spells unconditional as an empty list rather than an absent key,
	// so a reader never has to guess which of the two it is looking at.
	if !strings.Contains(string(raw), "profiles = []") {
		t.Errorf("an unconditional entry did not write `profiles = []`:\n%s", raw)
	}

	back, err := Read(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(back.Resolved, l.Resolved) {
		t.Errorf("round trip changed the entries:\n got %+v\nwant %+v", back.Resolved, l.Resolved)
	}
	if back.RepoClassName != "hmd-ms-myapi" || back.GeneratedFrom != "env:dev" {
		t.Errorf("round trip lost the header: %+v", back)
	}
}

// A lock declaring a schema version nsctl does not know is refused with the
// version found and the versions supported -- and never partially honoured,
// because a silently-ignored `resolved` entry is a missing instance nobody goes
// looking for.
func TestUnknownSchemaVersionIsRefusedNotPartiallyRead(t *testing.T) {
	t.Parallel()

	l, err := Parse([]byte(`
version = 7
repo_class_name = "hmd-ms-myapi"
generated_from = "pins"

[[resolved]]
repo_class_name = "hmd-inf-trino"
version = "0.3.12"
profiles = []
content_path = "repository:/hmd-inf-trino/0.3.12/hmd-inf-trino_0.3.12_build.zip"
`))
	if err == nil {
		t.Fatal("succeeded, want a refusal")
	}
	if !strings.Contains(err.Error(), "7") || !strings.Contains(err.Error(), "1") {
		t.Errorf("error %q names neither the version found nor the one supported", err)
	}
	// The half-read case is the dangerous one: an entry that came back would be
	// deployed, and one that did not would simply be absent.
	if l != nil {
		t.Errorf("refused but still returned %d entries", len(l.Resolved))
	}
}

// Activation is a read-time filter. A lock that covered only the profile in use
// when it was generated would force a re-resolve -- a network trip, and
// therefore a different answer -- the first time anybody switched.
func TestBuildPinsEveryProfileNotOnlyTheActive(t *testing.T) {
	t.Parallel()

	l, _, err := Build("hmd-ms-myapi", "pins", []localspec.Want{
		want("app-db", "hmd-inf-postgres", "0.8.1", nil, nil),
		want("ms-transform", "hmd-ms-transform", "0.5.201", []string{"transforms"}, nil),
		want("otel", "hmd-inf-otel-collector", "0.1.7", []string{"telemetry"}, []string{"otel"}),
	}, pinned(map[string]string{
		"hmd-inf-postgres": "0.8.1", "hmd-ms-transform": "0.5.201", "hmd-inf-otel-collector": "0.1.7"}))
	if err != nil {
		t.Fatal(err)
	}
	if len(l.Resolved) != 3 {
		t.Fatalf("pinned %d entries, want all 3 regardless of profile", len(l.Resolved))
	}
	if got := l.AllProfiles(); !reflect.DeepEqual(got, []string{"telemetry", "transforms"}) {
		t.Errorf("AllProfiles = %v, want both profiles the lock mentions", got)
	}
}

// One repo class filling several roles is one pinned version and several roles,
// which is why the lock is keyed by class and `satisfies` is a list.
// hmd-inf-credentials does this three times in hmd-inf-trino.
func TestBuildGroupsOneClassAcrossRoles(t *testing.T) {
	t.Parallel()

	l, _, err := Build("hmd-inf-trino", "pins", []localspec.Want{
		want("users", "hmd-inf-credentials", "0.1.9", nil, []string{"users"}),
		want("ro-users", "hmd-inf-credentials", "0.1.9", []string{"readonly"}, []string{"ro-users"}),
		want("adhoc-users", "hmd-inf-credentials", "0.1.9", nil, []string{"adhoc-users"}),
	}, pinned(map[string]string{"hmd-inf-credentials": "0.1.9"}))
	if err != nil {
		t.Fatal(err)
	}
	if len(l.Resolved) != 1 {
		t.Fatalf("pinned %d entries, want 1 -- a lock pins a class, not an instance", len(l.Resolved))
	}
	e := l.Resolved[0]
	if !reflect.DeepEqual(e.Satisfies, []string{"adhoc-users", "ro-users", "users"}) {
		t.Errorf("satisfies = %v, want all three roles sorted", e.Satisfies)
	}
	// One unconditional want makes the class unconditional: profiles are a
	// filter, and something that always starts cannot be filtered out by a
	// profile another entry named.
	if len(e.Profiles) != 0 {
		t.Errorf("profiles = %v, want [] -- two of the three wants are unconditional", e.Profiles)
	}
}

func TestBuildUnionsProfilesAcrossGatedWants(t *testing.T) {
	t.Parallel()

	l, _, err := Build("x", "pins", []localspec.Want{
		want("a", "hmd-inf-thing", "0.1.0", []string{"full"}, nil),
		want("b", "hmd-inf-thing", "0.1.0", []string{"telemetry", "full"}, nil),
	}, pinned(map[string]string{"hmd-inf-thing": "0.1.0"}))
	if err != nil {
		t.Fatal(err)
	}
	if got := l.Resolved[0].Profiles; !reflect.DeepEqual(got, []string{"full", "telemetry"}) {
		t.Errorf("profiles = %v, want the sorted union", got)
	}
}

// A lock cannot pin one class twice, so two wants of it that resolve apart is a
// refusal naming both rather than whichever the map happened to yield.
func TestBuildRefusesOneClassAtTwoVersions(t *testing.T) {
	t.Parallel()

	_, _, err := Build("x", "pins", []localspec.Want{
		want("a", "hmd-inf-thing", "0.1.0", nil, nil),
		want("b", "hmd-inf-thing", "0.2.0", nil, nil),
	}, func(w localspec.Want) string { return w.VersionSpec })
	if err == nil {
		t.Fatal("succeeded, want a refusal")
	}
	for _, s := range []string{"hmd-inf-thing", "0.1.0", "0.2.0"} {
		if !strings.Contains(err.Error(), s) {
			t.Errorf("error %q does not name %q", err, s)
		}
	}
}

func TestBuildReportsWhatItCouldNotResolve(t *testing.T) {
	t.Parallel()

	l, unresolved, err := Build("x", "pins", []localspec.Want{
		want("a", "hmd-inf-pinned", "0.1.0", nil, nil),
		want("b", "hmd-ms-ranged", "~= 0.5", nil, nil),
	}, pinned(map[string]string{"hmd-inf-pinned": "0.1.0"}))
	if err != nil {
		t.Fatal(err)
	}
	if len(unresolved) != 1 || unresolved[0].RepoClassName != "hmd-ms-ranged" {
		t.Fatalf("unresolved = %+v, want the one range", unresolved)
	}
	// What did resolve still comes back, so a caller can report every failure at
	// once instead of one per run.
	if len(l.Resolved) != 1 {
		t.Errorf("pinned %d entries, want the one that resolved", len(l.Resolved))
	}
}

// The two directions have different fixes, so Check reports them separately.
func TestCheckFindsBothDirections(t *testing.T) {
	t.Parallel()

	l, _, err := Build("x", "pins", []localspec.Want{
		want("a", "hmd-inf-kept", "0.1.0", nil, nil),
		want("b", "hmd-inf-dropped", "0.1.0", nil, nil),
	}, pinned(map[string]string{"hmd-inf-kept": "0.1.0", "hmd-inf-dropped": "0.1.0"}))
	if err != nil {
		t.Fatal(err)
	}

	missing, extra := Check(l, []localspec.Want{
		want("a", "hmd-inf-kept", "0.1.0", nil, nil),
		want("c", "hmd-inf-added", "0.1.0", nil, nil),
	})
	if !reflect.DeepEqual(missing, []string{"hmd-inf-added"}) {
		t.Errorf("missing = %v, want the newly declared class", missing)
	}
	if !reflect.DeepEqual(extra, []string{"hmd-inf-dropped"}) {
		t.Errorf("extra = %v, want the class no longer declared", extra)
	}
}

func TestCheckOnACurrentLockFindsNothing(t *testing.T) {
	t.Parallel()

	wants := []localspec.Want{want("a", "hmd-inf-kept", "0.1.0", nil, nil)}
	l, _, err := Build("x", "pins", wants, pinned(map[string]string{"hmd-inf-kept": "0.1.0"}))
	if err != nil {
		t.Fatal(err)
	}
	if missing, extra := Check(l, wants); len(missing) != 0 || len(extra) != 0 {
		t.Errorf("Check on a current lock = %v, %v; want nothing", missing, extra)
	}
}

// Absent is a distinguishable outcome, because its fix is `nsctl lock` and a
// malformed lock's is not.
func TestReadReportsAbsenceDistinctly(t *testing.T) {
	t.Parallel()

	_, err := Read(t.TempDir())
	if !errors.Is(err, ErrAbsent) {
		t.Fatalf("Read on a repo with no lock = %v, want ErrAbsent", err)
	}
}

func TestEntryLookup(t *testing.T) {
	t.Parallel()

	l, _, err := Build("x", "pins", []localspec.Want{want("a", "hmd-inf-kept", "0.1.0", nil, nil)},
		pinned(map[string]string{"hmd-inf-kept": "0.1.0"}))
	if err != nil {
		t.Fatal(err)
	}
	if e, ok := l.Entry("hmd-inf-kept"); !ok || e.Version != "0.1.0" {
		t.Errorf("Entry = %+v, %v", e, ok)
	}
	if _, ok := l.Entry("hmd-inf-absent"); ok {
		t.Error("Entry found a class the lock does not pin")
	}
}

// Deterministic output: a lock generated twice from one manifest is the same
// bytes, or every regeneration is a diff and nobody reviews them.
func TestBuildIsDeterministic(t *testing.T) {
	t.Parallel()

	wants := []localspec.Want{
		want("z", "hmd-inf-zebra", "0.1.0", nil, nil),
		want("a", "hmd-inf-alpha", "0.2.0", nil, nil),
		want("m", "hmd-inf-mike", "0.3.0", nil, nil),
	}
	versions := pinned(map[string]string{
		"hmd-inf-zebra": "0.1.0", "hmd-inf-alpha": "0.2.0", "hmd-inf-mike": "0.3.0"})

	first, _, err := Build("x", "pins", wants, versions)
	if err != nil {
		t.Fatal(err)
	}
	var classes []string
	for _, e := range first.Resolved {
		classes = append(classes, e.RepoClassName)
	}
	if !reflect.DeepEqual(classes, []string{"hmd-inf-alpha", "hmd-inf-mike", "hmd-inf-zebra"}) {
		t.Errorf("entries = %v, want them sorted by class", classes)
	}
}

// A bound want is filled by an instance the environment provides. Nothing of
// its class is deployed for it, so the lock neither pins it nor reports it
// unresolved -- a pin nobody reads would only go stale -- and Check does not
// count it as declared.
func TestBuildAndCheckSkipABoundWant(t *testing.T) {
	t.Parallel()

	compute := want("compute", "hmd-inf-eks-node-group", "~= 0.1", nil, []string{"compute"})
	compute.Bind = "local-neuronsphere"
	wants := []localspec.Want{
		want("app-store", "hmd-inf-s3bucket", "0.1.13", nil, []string{"app-store"}),
		compute,
	}

	l, unresolved, err := Build("hmd-ms-myapi", "pins", wants,
		pinned(map[string]string{"hmd-inf-s3bucket": "0.1.13"}))
	if err != nil {
		t.Fatal(err)
	}
	if len(unresolved) != 0 {
		t.Errorf("unresolved = %v, want the bound want skipped rather than reported", unresolved)
	}
	if _, pinnedIt := l.Entry("hmd-inf-eks-node-group"); pinnedIt {
		t.Error("the lock pins hmd-inf-eks-node-group, which is bound and never deployed")
	}
	if missing, _ := Check(l, wants); len(missing) != 0 {
		t.Errorf("Check reports %v missing, want a bound want not counted", missing)
	}
}
