package versionspec

import (
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
)

// goldenCase is one observation of the Python evaluator. See
// testdata/generate_golden.py for what each outcome means.
type goldenCase struct {
	Spec    string `json:"spec"`
	Version string `json:"version"`
	Outcome string `json:"outcome"`
}

// TestGoldenTable is the contract with hmd-ms-deployment.
//
// Every case was generated by running hmd_ms_deployment.version.VersionSpecifier
// over the same pair, so a drift between the two evaluators fails here rather
// than as a deploy that is refused after nsctl said yes. NERD011's risk table
// rates that drift High, and this is its whole mitigation.
//
// Regenerate rather than edit:
//
//	python3 internal/versionspec/testdata/generate_golden.py
func TestGoldenTable(t *testing.T) {
	t.Parallel()

	data, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatalf("reading the golden table: %v", err)
	}
	var table struct {
		Source string       `json:"source"`
		Cases  []goldenCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &table); err != nil {
		t.Fatalf("parsing the golden table: %v", err)
	}
	if len(table.Cases) == 0 {
		t.Fatal("the golden table is empty")
	}

	for _, c := range table.Cases {
		t.Run(c.Spec+" "+c.Version, func(t *testing.T) {
			t.Parallel()

			spec, parseErr := Parse(c.Spec)

			// The one deliberate divergence, and it is SPEC002's whole point.
			// An ordered specifier is refused here whatever the Python did with
			// it -- including the three shapes that parse and then compare
			// component-wise. When Ordered is fixed upstream these rows become
			// live and this branch is what gets deleted.
			if ordered(c.Spec) {
				if !errors.Is(parseErr, ErrOrdered) {
					t.Fatalf("Parse(%q) = %v, want ErrOrdered", c.Spec, parseErr)
				}
				return
			}

			if c.Outcome == "spec_error" {
				if parseErr == nil {
					t.Fatalf("Parse(%q) succeeded; the Python refuses it", c.Spec)
				}
				return
			}
			if parseErr != nil {
				t.Fatalf("Parse(%q) = %v; the Python accepts it", c.Spec, parseErr)
			}

			got := spec.Satisfies(c.Version)
			// reject and version_error are both "not satisfied" here: one is
			// the evaluator's own exception and the other is an IndexError or
			// an AssertionError, and a version the control plane cannot
			// evaluate is one nsctl must never select.
			want := c.Outcome == "accept"
			if got != want {
				t.Errorf("Parse(%q).Satisfies(%q) = %v, want %v (python: %s)",
					c.Spec, c.Version, got, want, c.Outcome)
			}
		})
	}
}

// ordered reports whether a specifier uses an operator this package refuses.
func ordered(spec string) bool {
	for _, clause := range strings.Split(strings.ReplaceAll(spec, " ", ""), ",") {
		if strings.HasPrefix(clause, ">") || strings.HasPrefix(clause, "<") {
			return true
		}
	}
	return false
}

// TestGoldenTableCoversSPEC002sCases pins the specific pairs the proposal lists,
// so that a regenerated table which quietly stopped covering them fails.
//
// The first two are the ones that surprise every reader: `~= 0.1` is not "the
// 0.1 series". An implementation that filtered by the "0.1." prefix would be
// wrong for every repo class that has reached 0.2 and accidentally right for one
// that has not, which is the worst way for a bug to behave.
func TestGoldenTableCoversSPEC002sCases(t *testing.T) {
	t.Parallel()

	required := []goldenCase{
		{"~= 0.1", "0.2.5", "accept"},
		{"~= 0.1", "0.9.99", "accept"},
		{"~= 0.1", "0.1.0", "accept"},
		{"~= 0.1", "0.1.225", "accept"},
		{"~= 0.1", "0.0.9", "reject"},
		{"~= 0.1", "1.0.0", "reject"},
		{"~= 0.1.7", "0.1.7", "accept"},
		{"~= 0.1.7", "0.1.225", "accept"},
		{"~= 0.1.7", "0.1.6", "reject"},
		{"~= 0.1.7", "0.2.0", "reject"},
		{"~= 0.1", "0.1.2.3", "accept"},
		{"== 0.1.*", "0.1", "accept"},
		{"~= 0.1,!= 0.1.5", "0.1.5", "reject"},
		{"~= 0.1,!= 0.1.5", "0.1.6", "accept"},
		{"~= 0.1", "abc", "version_error"},
		// The five wrong comparisons, recorded as evidence for the refusal.
		{"< 0.3.0", "0.2.9", "reject"},
		{"> 0.1.0", "1.0.0", "reject"},
		{"<= 0.2.0", "0.1.9", "reject"},
		{">= 0.3", "0.3.1", "spec_error"},
	}

	data, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatalf("reading the golden table: %v", err)
	}
	var table struct {
		Cases []goldenCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &table); err != nil {
		t.Fatalf("parsing the golden table: %v", err)
	}
	observed := map[goldenCase]bool{}
	for _, c := range table.Cases {
		observed[c] = true
	}
	for _, c := range required {
		if !observed[c] {
			t.Errorf("the golden table does not record %q against %q as %s",
				c.Spec, c.Version, c.Outcome)
		}
	}
}
