"""LocalWorkflowRunner for executing deployment DAGs locally.

Replaces Argo workflow execution in local extend mode. For each node
in the deployment manifest (generated by ms-deployment), the runner
resolves the repo's deploy strategy and either skips the node or runs
the deploy script in an hmd-img-projectbuilder container against the
workload Floci instance.

Strategy resolution is 3-tier:
1. Per-repo ``src/local/nsplugin.json`` ``local_deploy.strategy``
2. Central ``local_overrides.json`` (fallback)
3. Default: ``"default"`` — attempt execution in projectbuilder
"""

import json
import logging
import os
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

import requests
from cement import minimal_logger

logger = minimal_logger("local_workflow_runner")

# Strategies that skip execution and mark DEPLOYED immediately
SKIP_STRATEGIES = {"skip", "local_storage"}


def _load_local_deploy_strategy(repo_class_name: str) -> Optional[str]:
    """Load the local_deploy.strategy from a repo's src/local/nsplugin.json.

    :param repo_class_name: The repo directory name (e.g., "hmd-vpc")
    :returns: The strategy string ("skip", "default", etc.) or None if not found
    """
    repo_home = os.environ.get("HMD_REPO_HOME", "")
    if not repo_home:
        return None

    nsplugin_path = (
        Path(repo_home) / repo_class_name / "src" / "local" / "nsplugin.json"
    )
    if not nsplugin_path.exists():
        return None

    try:
        with open(nsplugin_path) as f:
            config = json.load(f)
        return config.get("local_deploy", {}).get("strategy")
    except (json.JSONDecodeError, KeyError):
        return None


class LocalWorkflowRunner:
    """Execute deployment DAG nodes locally using Docker containers.

    Strategy handlers:
    - "skip": Mark DEPLOYED without executing (cloud-only infrastructure)
    - "local_storage": Mark DEPLOYED (storage provisioner handled it)
    - "compose_substitute": Mark DEPLOYED (compose container already started)
    - "default" / None: Run deploy script in projectbuilder against workload Floci
    """

    def __init__(self, base_url: str, overrides: Dict = None):
        """
        :param base_url: ms-deployment base URL (e.g., http://localhost/hmd_ms_deployment)
        :param overrides: Central local_overrides.json dict (fallback for repos without nsplugin.json)
        """
        self.base_url = base_url
        self.overrides = overrides or {}

    def _resolve_strategy(self, repo_class_name: str) -> str:
        """Resolve the deploy strategy for a repo class (3-tier lookup).

        1. Per-repo src/local/nsplugin.json local_deploy.strategy
        2. Central local_overrides.json
        3. Default: "default"
        """
        # Tier 1: per-repo nsplugin.json
        strategy = _load_local_deploy_strategy(repo_class_name)
        if strategy is not None:
            return strategy

        # Tier 2: central overrides
        if repo_class_name in self.overrides:
            strategy = self.overrides[repo_class_name].get("strategy")
            if strategy is not None:
                return strategy

        # Tier 3: default — attempt execution in projectbuilder
        return "default"

    def run(self, csd_nid: str, nodes: List[Dict]) -> bool:
        """Execute deployment nodes in DAG order.

        :param csd_nid: The ChangeSetDeployment identifier
        :param nodes: Ordered list of node descriptors from generate_local_deployment
        :returns: True if all nodes succeeded
        """
        self._set_csd_status(csd_nid, "STARTED")

        # Log strategy summary
        strategy_counts: Dict[str, int] = {}
        for node in nodes:
            s = self._resolve_strategy(node["repo_class_name"])
            strategy_counts[s] = strategy_counts.get(s, 0) + 1
        summary = ", ".join(f"{k}: {v}" for k, v in sorted(strategy_counts.items()))
        logger.info(f"Strategy summary: {summary}")
        print(f"  Strategy summary: {summary}")

        for node in nodes:
            instance_name = node["instance_name"]
            repo_class_name = node["repo_class_name"]
            rid_nid = node["rid_nid"]
            strategy = self._resolve_strategy(repo_class_name)

            if strategy in SKIP_STRATEGIES:
                logger.info(f"SKIP: {instance_name} ({repo_class_name}) [{strategy}]")
                print(f"  SKIP: {instance_name} ({repo_class_name})")
                self._set_status(rid_nid, "DEPLOYED")
                continue

            if strategy == "compose_substitute":
                logger.info(
                    f"COMPOSE: {instance_name} ({repo_class_name}) — container already started"
                )
                print(f"  COMPOSE: {instance_name} ({repo_class_name})")
                self._set_status(rid_nid, "DEPLOYED")
                continue

            # strategy == "default" or anything else: execute in projectbuilder
            logger.info(f"DEPLOY: {instance_name} ({repo_class_name})")
            print(f"  DEPLOY: {instance_name} ({repo_class_name})")

            success = self._execute_in_projectbuilder(node)
            if success:
                self._set_status(rid_nid, "DEPLOYED")
            else:
                self._set_status(rid_nid, "FAILED")
                self._set_csd_status(csd_nid, "FAILED")
                logger.error(f"FAILED: {instance_name} ({repo_class_name})")
                print(f"  FAILED: {instance_name}")
                return False

        self._set_csd_status(csd_nid, "COMPLETED")
        return True

    def _execute_in_projectbuilder(self, node: Dict) -> bool:
        """Run a deploy script in an hmd-img-projectbuilder container.

        The container runs on the neuronsphere_default network with
        AWS_ENDPOINT_URL pointing to the workload Floci instance so
        CDKTF and other AWS tools target the local emulator.
        """
        registry = os.environ.get(
            "HMD_LOCAL_NS_CONTAINER_REGISTRY", "ghcr.io/neuronsphere"
        )
        pb_version = os.environ.get("HMD_PROJECTBUILDER_VERSION", "stable")
        image = f"{registry}/hmd-img-projectbuilder:{pb_version}"

        script = node.get("script", "")
        if not script:
            logger.warning(f"No script for node {node['instance_name']}, skipping")
            return True

        repo_class_name = node["repo_class_name"]
        repo_home = os.environ.get("HMD_REPO_HOME", "")

        # Workload Floci endpoint (separate from admin Floci); resolved via
        # the `neuronsphere-workload` Docker network alias.
        workload_endpoint = os.environ.get(
            "FLOCI_WORKLOAD_ENDPOINT_DOCKER", "http://neuronsphere-workload:4566"
        )

        cmd = [
            "docker",
            "run",
            "--rm",
            "--network",
            "neuronsphere_default",
            "-e",
            f"AWS_ENDPOINT_URL={workload_endpoint}",
            "-e",
            f"AWS_ACCESS_KEY_ID={os.environ.get('AWS_ACCESS_KEY_ID', 'dummykey')}",
            "-e",
            f"AWS_SECRET_ACCESS_KEY={os.environ.get('AWS_SECRET_ACCESS_KEY', 'dummykey')}",
            "-e",
            f"AWS_DEFAULT_REGION={os.environ.get('AWS_REGION', 'us-west-2')}",
            "-e",
            "HMD_ENVIRONMENT=local",
            "-e",
            f"HMD_CUSTOMER_CODE={os.environ.get('HMD_CUSTOMER_CODE', 'none')}",
            "-e",
            f"HMD_DID={os.environ.get('HMD_DID', 'aaa')}",
            "-e",
            f"HMD_REGION={os.environ.get('HMD_REGION', 'reg1')}",
            "-e",
            f"HMD_HOSTNAME={os.environ.get('HMD_HOSTNAME', 'localhost')}",
            "-v",
            "/var/run/docker.sock:/var/run/docker.sock",
        ]

        # Mount the repo source code if available
        if repo_home and repo_class_name:
            repo_path = os.path.join(repo_home, repo_class_name)
            if os.path.isdir(repo_path):
                cmd.extend(["-v", f"{repo_path}:/workspace"])
                cmd.extend(["-w", "/workspace"])

        cmd.extend([image, "bash", "-c", script])

        logger.info(f"Running projectbuilder for {node['instance_name']}")
        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            logger.error(
                f"Projectbuilder failed for {node['instance_name']}: "
                f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
            )
        else:
            logger.info(f"Projectbuilder succeeded for {node['instance_name']}")

        return result.returncode == 0

    def _set_status(self, rid_nid: str, status: str):
        """Update a RepoInstanceDeployment status."""
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_deployment_status/{rid_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.error(f"Failed to set RID status {rid_nid} to {status}: {e}")

    def _set_csd_status(self, csd_nid: str, status: str):
        """Update a ChangeSetDeployment status."""
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_change_set_deployment_status/{csd_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.error(f"Failed to set CSD status {csd_nid} to {status}: {e}")
