"""LocalWorkflowRunner for executing deployment DAGs locally.

Replaces Argo workflow execution in local extend mode. For each node in the
deployment manifest (generated by ms-deployment), the runner runs the deploy
script in an hmd-img-projectbuilder container against the single Floci
instance -- except the single core node for ``bom_seeder.CORE_REPO_CLASS``
(``hmd-cli-neuronsphere``), which only ever anchors the core-resource-producing
instance (see ``bom_seeder.LOCAL_CORE_BOM``) and is marked DEPLOYED directly
without executing anything.
"""

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import requests
import yaml
from cement import minimal_logger

from .bom_seeder import CORE_REPO_CLASS
from .floci_deployer import DOCKER_NETWORK_NAME, K3S_CLUSTER_NAME
from .image_cache import (
    ImageUnavailable,
    _image_cached,
    _is_truthy,
    _tag,
    container_cli,
    ensure_lambda_image,
    image_candidates,
)
from .startup_display import spinner_step

logger = minimal_logger("local_workflow_runner")

# Directories that are never worth copying into an overlay workspace (build
# output, VCS metadata, dependency caches). Keeps the temp copy small/fast.
_OVERLAY_COPY_IGNORE = shutil.ignore_patterns(
    ".git",
    "node_modules",
    "build",
    "target",
    "dist",
    "cdktf.out",
    ".terraform",
    "__pycache__",
    "*.egg-info",
)


# Matches the `hmd ... deploy` command line the ms-deployment generator emits
# (deploy_base.deploy_node), so `--local` is inserted right after the `deploy`
# subcommand. Anchored on a line that starts with `hmd ` (export / heredoc / config
# lines don't), and requires a following flag/whitespace so we don't match a value
# that merely ends in "deploy".
_DEPLOY_CMD_RE = re.compile(r"^(\s*hmd\b.*?\sdeploy)(\s|$)")


@dataclass
class _NodeResult:
    """Outcome of running one node's deploy script in a projectbuilder container.

    Carries enough of the subprocess result for the caller to print a terse
    success line (resource_count) or, on failure, the full diagnostic detail
    (returncode/stdout/stderr) -- without printing either eagerly itself.
    """

    success: bool
    resource_count: int = 0
    returncode: Optional[int] = None
    stdout: str = ""
    stderr: str = ""


def _print_failure_detail(instance_name: str, result: "_NodeResult") -> None:
    """Print a node's captured output below its ``✗`` line.

    The happy path is now a single terse line per node, so a failure must not
    lose the diagnostic payload -- it's just deferred to print in full here,
    directly under the failed node, instead of eagerly during the run.
    """
    header = f"exit {result.returncode}" if result.returncode is not None else "failed"
    print(f"\n  --- {instance_name} {header} ---")
    if result.stdout.strip():
        print(result.stdout.rstrip())
    if result.stderr.strip():
        print(result.stderr.rstrip())
    print(f"  --- end {instance_name} output ---\n")


def _localize_deploy_script(script: str) -> str:
    """Make a generated deploy node script deploy from the mounted source.

    The generated script runs a bare ``hmd ... deploy ...`` (no source flag), which
    makes hmd-cli-deploy pull the build bundle from the Artifact Librarian — absent
    locally. Insert ``--local`` after the ``deploy`` subcommand so hmd-cli-deploy
    deploys from the current working directory (the mounted ``/workspace``). Only the
    command line is transformed (once); ``export``/heredoc/config lines are untouched.
    Idempotent — a no-op when ``--local`` is already present.
    """
    if not script:
        return script
    out_lines = []
    done = False
    for line in script.splitlines():
        if not done:
            m = _DEPLOY_CMD_RE.match(line)
            if m and "--local" not in line:
                line = f"{m.group(1)} --local{m.group(2)}{line[m.end():]}"
                done = True
            elif m:
                done = True  # already localized
        out_lines.append(line)
    return "\n".join(out_lines)


def _repo_path_for(repo_class_name: str) -> Optional[str]:
    """Return the HMD_REPO_HOME path for a repo class, if it exists locally."""
    repo_home = os.environ.get("HMD_REPO_HOME", "")
    if not repo_home or not repo_class_name:
        return None
    candidate = os.path.join(repo_home, repo_class_name)
    return candidate if os.path.isdir(candidate) else None


def _overlay_dir_for(repo_path: Optional[str]) -> Optional[Path]:
    """Return the ``src/local`` overlay directory for a repo path, if present.

    A repo may ship Floci-safe alternates under ``src/local`` that overlay its
    real deploy sources at local-deploy time:

      src/local/deploy_local.sh    full deploy-script override (highest priority)
      src/local/cdktf/             alternate CdkTf stack, overlays src/cdktf/
      src/local/helm/              alternate helm chart/values, overlays src/helm/
      src/local/config_local.json  overlays meta-data/config_local.json
    """
    if not repo_path:
        return None
    overlay = Path(repo_path) / "src" / "local"
    return overlay if overlay.is_dir() else None


def _overlay_has_tool_files(overlay_dir: Path) -> bool:
    """True if the overlay contains cdktf/helm/config alternates to apply."""
    return (
        (overlay_dir / "cdktf").is_dir()
        or (overlay_dir / "helm").is_dir()
        or (overlay_dir / "config_local.json").is_file()
    )


# Escape hatch: proceed with a warning instead of failing a node whose Lambda
# image could not be staged. Matches the advisory posture the rest of the local
# image handling takes (hmd_cli_docker.deploy_local, hmd-cli-helm's k3s import).
SKIP_IMAGE_PREPULL_ENV = "HMD_LOCAL_SKIP_IMAGE_PREPULL"


def _deploys_lambda_image(repo_dir: Optional[str]) -> bool:
    """True if this repo's deploy builds a Floci Lambda from a Docker image.

    That is exactly the set with ``docker`` among its BACON ``deploy.commands``.
    An unreadable manifest (a repo deployed from a bundle with no resolvable
    tree) returns False, leaving the node to behave as it did before staging
    existed.
    """
    if not repo_dir:
        return False
    try:
        with open(os.path.join(repo_dir, "meta-data", "manifest.json")) as f:
            manifest = json.load(f)
    except (OSError, ValueError):
        return False
    commands = (manifest.get("deploy") or {}).get("commands") or []
    return any(
        (cmd[0] if isinstance(cmd, list) and cmd else cmd) == "docker"
        for cmd in commands
    )


def _chart_image_repository(repo_dir: Optional[str]) -> Optional[str]:
    """The image repository this repo's Helm chart deploys, if it has one.

    That is a repo with ``helm`` among its BACON ``deploy.commands`` *and* an
    ``image.repository`` in its ``deploy.default_configuration`` -- the value the
    chart renders into the pod spec. A chart that names no image of its own (a
    CRDs chart, an operator wrapper) has nothing to stage.

    An unreadable manifest returns None, leaving the node to behave as it did
    before staging existed.
    """
    if not repo_dir:
        return None
    try:
        with open(os.path.join(repo_dir, "meta-data", "manifest.json")) as f:
            manifest = json.load(f)
    except (OSError, ValueError):
        return None
    deploy = manifest.get("deploy") or {}
    commands = deploy.get("commands") or []
    deploys_helm = any(
        (cmd[0] if isinstance(cmd, list) and cmd else cmd) == "helm" for cmd in commands
    )
    if not deploys_helm:
        return None
    image = (deploy.get("default_configuration") or {}).get("image") or {}
    return image.get("repository") or None


def _import_image_into_k3s(ref: str, container: str, cli: str) -> bool:
    """``docker save <ref> | <cli> exec -i <container> ctr -n k8s.io images import -``.

    k3s serves pods from its own containerd namespace (``k8s.io``), which the host
    daemon's cache is invisible to. Streaming rather than writing a tar keeps a
    multi-hundred-MB image off disk.
    """
    already = subprocess.run(
        [cli, "exec", container, "ctr", "-n", "k8s.io", "images", "ls", "-q"],
        capture_output=True,
        text=True,
    )
    if already.returncode == 0 and ref in (already.stdout or ""):
        logger.debug(f"{ref} is already in {container}'s containerd")
        return True

    logger.debug(f"Importing {ref} into {container}'s containerd")
    saved = subprocess.Popen([cli, "save", ref], stdout=subprocess.PIPE)
    imported = subprocess.Popen(
        [cli, "exec", "-i", container, "ctr", "-n", "k8s.io", "images", "import", "-"],
        stdin=saved.stdout,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if saved.stdout is not None:
        saved.stdout.close()
    _, stderr = imported.communicate()
    saved.wait()
    if imported.returncode != 0:
        logger.warning(
            f"Could not import {ref} into {container}: "
            f"{(stderr or b'').decode().strip()}"
        )
        return False
    return True


class LocalWorkflowRunner:
    """Execute deployment DAG nodes locally using Docker containers.

    Every node runs the real deploy script in projectbuilder against the
    single Floci, applying any ``src/local`` Floci-safe overlay for the repo
    -- except a node for ``bom_seeder.CORE_REPO_CLASS`` (``hmd-cli-neuronsphere``
    itself), which is marked DEPLOYED directly: that RepoClass only ever
    anchors the core-resource-producing instance (see
    ``bom_seeder.LOCAL_CORE_BOM``) and has nothing to actually deploy.
    """

    def __init__(
        self,
        base_url: str,
        cluster_name: str = None,
        env=None,
        repo_paths=None,
        verbose: bool = False,
        tracking: bool = True,
    ):
        """
        :param base_url: ms-deployment base URL (e.g., http://localhost/hmd_ms_deployment)
        :param cluster_name: The local k3s cluster name, used to rewrite the mounted
            kubeconfig's server to the in-network Floci EKS alias (see
            _kubeconfig_for_container). Without it, nodes fall back to the raw
            kubeconfig's host-only server, which is unreachable from in-container.
        :param env: The named local environment being deployed into. Selects the
            Floci account the deploy targets, the deployment id, and the
            kubeconfig -- all of which differ per environment.
        :param repo_paths: Optional ``repo_class_name`` -> working-tree overrides
            for repo instances an environment manifest declares with an explicit
            ``source.path``, which by definition are not under ``HMD_REPO_HOME``
            where :func:`_repo_path_for` would find them.
        :param verbose: Disables per-node spinner animation in favor of plain
            start/result lines -- set from the `up`/`down` command's own
            --verbose flag, for log- and CI-friendly output.
        :param tracking: When False, status updates and produced Resources are
            buffered instead of POSTed, to be flushed later by
            :meth:`replay_into`. This is what lets the control-plane bootstrap
            DAG run *before* ``hmd-ms-deployment`` exists -- it is the last node
            in that DAG -- and still record every node that ran once it does.
            Without it the three callbacks would simply fail their connections
            and the bootstrap instances would never appear in the deployment
            graph at all.
        """
        self.base_url = base_url
        self.env = env
        self.cluster_name = cluster_name or (env.k3s_cluster if env else None)
        self.repo_paths = dict(repo_paths or {})
        self.verbose = verbose
        self.tracking = tracking
        # True only while replay_into is flushing, so a 404 for an entity that was
        # never registered can be logged as the known gap it is rather than as a
        # failure of this run.
        self._replaying = False
        # (method_name, args) recorded while tracking is off, replayed in order
        # by replay_into(). Ordering matters: a Resource submission is keyed by
        # the RepoInstanceDeployment id its status update settles.
        self._deferred: List[Tuple[str, tuple]] = []
        # Instance names the most recent run() settled successfully. A partial
        # run is normal (the DAG stops at the first failure), and the reconcile
        # snapshot must record exactly what landed -- no more, so a failed entry
        # stays eligible for retry, and no less, so a succeeded one is not
        # redeployed on every subsequent `up`.
        self.last_succeeded: List[str] = []

    def env_route_prefix(self) -> str:
        """The nginx path prefix this environment's services are routed under.

        Only the control plane (ms-deployment, ms-naming, artifact-lib) is served
        unprefixed. Everything belonging to an environment -- ms-dbaccount above
        all, since it is per-environment exactly as in the cloud -- lives at
        ``/<slug>/<service>/``; ``nginx_router.write_env_routes`` prefixes every
        environment, legacy layout included.
        """
        if self.env is None:
            return ""
        return f"/{self.env.slug}"

    def ns_local_proxy(self) -> str:
        """Container-reachable root a deploy tool joins ``/hmd_ms_<svc>/…`` onto.

        Host-side the local nginx is ``localhost``; inside the projectbuilder
        container it is the ``hmd_proxy`` container on the NeuronSphere network.
        The environment's route prefix is included because the services reached
        this way are the environment's own -- ``hmd-cli-dbaccount``'s local
        branch POSTs to ``{NS_LOCAL_PROXY}/hmd_ms_dbaccount/api/create_db_account``,
        and without the prefix that is a control-plane path where ms-dbaccount is
        not routed at all.

        Distinct from ``HMD_DEPLOYMENT_SERVICE_URL``, which addresses
        ms-deployment: that one *is* control-plane, and stays unprefixed.
        """
        override = os.environ.get("NS_LOCAL_PROXY")
        if override:
            return override
        root = (
            self.base_url.split("/hmd_ms_deployment")[0]
            .replace("localhost", "hmd_proxy")
            .replace("127.0.0.1", "hmd_proxy")
            .rstrip("/")
        )
        return f"{root}{self.env_route_prefix()}"

    def _repo_path(self, repo_class_name: str) -> Optional[str]:
        """The directory to mount and deploy ``repo_class_name`` from.

        The artifact bundled with the plugin package wins, so the code that
        deploys is the build the node is registered as; a working tree is
        mounted only under a local version override. See
        :func:`bom_seeder.repo_root_candidates`.
        """
        from .bom_seeder import repo_root_candidates

        declared = self.repo_paths.get(repo_class_name)
        candidates = repo_root_candidates(
            repo_class_name,
            repo_path=declared if declared and os.path.isdir(declared) else None,
        )
        return candidates[0] if candidates else None

    def run(self, csd_nid: str, nodes: List[Dict], destroy: bool = False) -> bool:
        """Execute deployment nodes in DAG order.

        :param csd_nid: The ChangeSetDeployment identifier
        :param nodes: Ordered list of node descriptors from generate_local_deployment
        :param destroy: Whether this is a destroy manifest. ms-deployment already
            emitted ``deploy --destroy`` scripts and ordered the DAG in reverse
            dependency order; what changes here is the status each node settles
            into (``DESTROYED``, not ``DEPLOYED``) and the fact that a teardown
            produces no Resources to submit.
        :returns: True if all nodes succeeded
        """
        verb = "DESTROY" if destroy else "DEPLOY"
        verb_ing = "Destroying" if destroy else "Deploying"
        success_status = "DESTROYED" if destroy else "DEPLOYED"
        final_csd_status = "DESTROYED" if destroy else "COMPLETED"
        succeeded: List[str] = []
        self.last_succeeded = succeeded

        self._set_csd_status(csd_nid, "STARTED")

        core_count = sum(1 for n in nodes if n["repo_class_name"] == CORE_REPO_CLASS)
        other_count = len(nodes) - core_count
        logger.debug(
            f"Node summary: {core_count} core (no-op), {other_count} {verb.lower()}"
        )
        summary = f"  {other_count} instance(s) to {verb.lower()}"
        if core_count:
            summary += f", {core_count} core"
        print(summary)

        for node in nodes:
            instance_name = node["instance_name"]
            repo_class_name = node["repo_class_name"]
            rid_nid = node["rid_nid"]

            if repo_class_name == CORE_REPO_CLASS:
                # The core instance anchors the local Resource graph and is never
                # torn down by a reconcile, so a core node in a destroy manifest
                # is still just a status flip -- no spinner, nothing to wait on.
                logger.debug(f"CORE: {instance_name} ({repo_class_name})")
                print(f"  ✔ {instance_name} (core)")
                self._set_status(rid_nid, success_status)
                succeeded.append(instance_name)
                continue

            with spinner_step(
                f"{verb_ing} {instance_name} ({repo_class_name})",
                verbose=self.verbose,
            ) as step:
                result = self._execute_node(node, destroy=destroy)
                if result.success:
                    self._set_status(rid_nid, success_status)
                    succeeded.append(instance_name)
                    ok_text = instance_name
                    if result.resource_count:
                        ok_text += f" ({result.resource_count} resource(s))"
                    step.ok(ok_text)
                else:
                    self._set_status(rid_nid, "FAILED")
                    self._set_csd_status(csd_nid, "FAILED")
                    step.fail(instance_name)
                    logger.error(f"FAILED: {instance_name} ({repo_class_name})")
                    _print_failure_detail(instance_name, result)
                    return False

        self._set_csd_status(csd_nid, final_csd_status)
        return True

    def _execute_node(self, node: Dict, destroy: bool = False) -> "_NodeResult":
        """Run one node, in a projectbuilder container or via a Python handler.

        A node may carry ``handler``: a callable taking ``(node, destroy)`` and
        returning True/False (or None for success). It exists for the
        control-plane bootstrap DAG, whose first nodes provision infrastructure
        the deployment service itself needs and so cannot yet be deployed
        *through* that service -- the core databases, and the control-plane
        Lambdas that `floci_deployer.setup_service` still installs directly.

        Keeping those as real DAG nodes rather than imperative pre-steps is the
        point: the DAG's shape (ms-deployment last, everything it depends on
        ahead of it) is correct from day one, and moving a node onto the
        projectbuilder path later is a per-node change here rather than a
        restructuring.
        """
        handler = node.get("handler")
        if handler is None:
            return self._execute_in_projectbuilder(node, destroy=destroy)
        try:
            ok = handler(node, destroy)
        except Exception as e:
            logger.error(f"Handler for {node['instance_name']} raised: {e}")
            return _NodeResult(False, stderr=str(e))
        return _NodeResult(ok is None or bool(ok))

    def _ensure_node_image(self, node: Dict) -> "tuple[bool, str]":
        """Stage the Docker image this node's Lambda will run from, on the host.

        Floci runs local Lambdas off the host Docker cache and is handed a bare
        ``<repo>:<version>`` tag (hmd-lib-cdktf-factories' ``lambda_function``).
        Nothing in the deploy path can put that tag there: the in-container
        ``hmd docker deploy`` has no Docker CLI to tag with. So the runner does
        it here, where a real Docker CLI exists, before the node runs.

        Failing here rather than letting the tag go unresolved turns a Floci
        "pull access denied" at Lambda-start time -- long after the node
        reported success -- into an actionable failure of the node itself.

        :returns: ``(True, "")`` to proceed with the node; ``(False, message)``
            to fail it. Returned rather than printed directly -- this runs
            while the node's spinner is animating (see ``run()``), and a raw
            ``print()`` there would collide with the spinner's own writes to
            stdout. The message is surfaced by the caller's ``_NodeResult``
            once the spinner has settled.
        """
        repo_class_name = node["repo_class_name"]
        repo_dir = self._repo_path(repo_class_name)
        if not _deploys_lambda_image(repo_dir):
            return True, ""

        version = node.get("repo_class_version")
        if not version:
            try:
                with open(os.path.join(repo_dir, "meta-data", "VERSION")) as f:
                    version = f.read().strip()
            except OSError:
                version = None
        if not version:
            logger.warning(
                f"No version resolved for {repo_class_name}; skipping image staging"
            )
            return True, ""

        try:
            staged = ensure_lambda_image(repo_class_name, version)
        except ImageUnavailable as e:
            if _is_truthy(os.environ.get(SKIP_IMAGE_PREPULL_ENV)):
                logger.warning(f"{e} ({SKIP_IMAGE_PREPULL_ENV} is set; continuing)")
                return True, ""
            logger.error(str(e))
            return False, str(e)

        logger.debug(f"Lambda image for {repo_class_name} staged as {staged}")
        return True, ""

    def _ensure_k3s_image(self, node: Dict) -> bool:
        """Import a locally-built chart image into the k3s node's containerd.

        Only relevant to the inner dev loop. Normally a chart's image is a
        published tag and k3s pulls it from the registry with the
        ``hmd-docker-repo-secret`` credentials; but when a repo is deployed from
        its working tree (``HMD_LOCAL_VERSION_<REPO_CLASS>=local`` or
        ``HMD_LOCAL_NEURONSPHERE_PREFER_LOCAL_VERSIONS``), the version resolves to
        one nothing has published and the image exists only in the host's docker
        cache.

        hmd-cli-helm has an importer for exactly this, but it cannot run in the
        deploy path: it needs a ``docker`` CLI to reach the host daemon, and the
        projectbuilder container ships nerdctl instead. So the runner does it here,
        on the host, before the node runs. ``image.pullPolicy=IfNotPresent`` is
        already forced for local deploys, so an imported image wins.

        Always returns True: a cache miss is the ordinary published-version path,
        and a failed import still leaves the registry pull to fall back on. Only
        :meth:`_ensure_node_image` (whose bare Lambda tag is unpullable by
        construction) can fail a node.
        """
        repo_class_name = node["repo_class_name"]
        repository = _chart_image_repository(self._repo_path(repo_class_name))
        if not repository:
            return True

        version = node.get("repo_class_version")
        if not version:
            logger.debug(f"No version resolved for {repo_class_name}; not importing")
            return True

        cli = container_cli()
        if not cli:
            return True

        # The ref the chart asks for: hmd-cli-helm passes the resolved version as
        # env.HMD_REPO_VERSION, which the pod spec uses as the tag.
        chart_ref = f"{repository}:{version}"

        # `ctr images import` names the image from the tar's own metadata, so the
        # host copy has to carry the chart's ref before it is saved. chart_ref is
        # last so an already-correct tag needs no re-tagging.
        sources = [
            ref
            for ref in image_candidates(repo_class_name, version) + [chart_ref]
            if _image_cached(ref, cli)
        ]
        if not sources:
            logger.debug(
                f"{chart_ref} is not in the host image cache; leaving the pull to k3s"
            )
            return True

        if sources[0] != chart_ref and not _tag(sources[0], chart_ref, cli):
            return True

        container = f"floci-eks-{self.cluster_name or K3S_CLUSTER_NAME}"
        _import_image_into_k3s(chart_ref, container, cli)
        return True

    def _prepare_overlay_workspace(self, repo_path: str, overlay_dir: Path) -> str:
        """Copy the repo to a temp dir and overlay its src/local alternates.

        Copies the repo (minus heavy/irrelevant dirs) so the developer's tree is
        never mutated, then overlays Floci-safe alternates on top:
          src/local/cdktf/*           -> src/cdktf/
          src/local/helm/*            -> src/helm/
          src/local/config_local.json -> meta-data/config_local.json

        :returns: Path to the prepared temp workspace (caller must clean it up)
        """
        tmp_root = tempfile.mkdtemp(prefix="ns-overlay-")
        workspace = os.path.join(tmp_root, os.path.basename(repo_path.rstrip("/")))
        shutil.copytree(repo_path, workspace, ignore=_OVERLAY_COPY_IGNORE)

        applied: List[str] = []
        for tool in ("cdktf", "helm"):
            src = overlay_dir / tool
            if src.is_dir():
                dest = Path(workspace) / "src" / tool
                dest.mkdir(parents=True, exist_ok=True)
                shutil.copytree(src, dest, dirs_exist_ok=True)
                applied.append(f"src/local/{tool} -> src/{tool}")

        cfg = overlay_dir / "config_local.json"
        if cfg.is_file():
            dest = Path(workspace) / "meta-data" / "config_local.json"
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(cfg, dest)
            applied.append("src/local/config_local.json -> meta-data/config_local.json")

        if applied:
            logger.debug(f"Applied src/local overlay: {', '.join(applied)}")
        return workspace

    def _execute_in_projectbuilder(
        self, node: Dict, destroy: bool = False
    ) -> "_NodeResult":
        """Run a deploy script in an hmd-img-projectbuilder container.

        The container runs on the neuronsphere_default network with
        AWS_ENDPOINT_URL pointing to the single Floci instance so CDKTF and
        other AWS tools target the local emulator. If the repo ships a
        ``src/local`` overlay, its Floci-safe alternates are applied first:
        a ``deploy_local.sh`` fully replaces the generated node script, and
        ``cdktf``/``helm``/``config_local.json`` overlay the real deploy sources
        in an isolated temp workspace (the developer's tree is never mutated).
        """
        registry = os.environ.get(
            "HMD_LOCAL_NS_CONTAINER_REGISTRY", "ghcr.io/neuronsphere"
        )
        pb_version = os.environ.get("HMD_PROJECTBUILDER_VERSION", "stable")
        image = f"{registry}/hmd-img-projectbuilder:{pb_version}"

        script = node.get("script", "")
        if not script:
            logger.warning(f"No script for node {node['instance_name']}, skipping")
            return _NodeResult(True)

        repo_class_name = node["repo_class_name"]

        # A destroy removes the Lambda, so it never needs the image.
        if not destroy:
            image_ok, image_err = self._ensure_node_image(node)
            if not image_ok:
                return _NodeResult(False, stderr=image_err)

        # Charts read their image from the k3s node's containerd, not the host's.
        if not destroy:
            self._ensure_k3s_image(node)

        # NERD0004/0006: expose a container-reachable Deployment Service URL so the
        # in-container `hmd deploy` can resolve dependency resource outputs (and,
        # opt-in, post produced Resources). `self.base_url` uses `localhost` (the
        # host nginx); inside the container the same nginx is the `hmd_proxy`
        # (alias `proxy`) container on neuronsphere_default — NOT `neuronsphere`,
        # which is the Floci alias on :4566. Overridable via env.
        rid_nid = node.get("rid_nid", "")
        deployment_service_url = os.environ.get(
            "HMD_DEPLOYMENT_SERVICE_URL",
            self.base_url.replace("localhost", "hmd_proxy").replace(
                "127.0.0.1", "hmd_proxy"
            ),
        )
        # Generic container-reachable root of the local proxy (nginx / `hmd_proxy`)
        # that fronts *every* local ms-* service's API Gateway route. Unlike
        # HMD_DEPLOYMENT_SERVICE_URL (ms-deployment-specific, and control-plane so
        # unprefixed), this is the shared base a deploy tool joins its own
        # `/hmd_ms_<svc>/...` path onto — e.g. hmd-cli-dbaccount's local branch
        # POSTs to `{NS_LOCAL_PROXY}/hmd_ms_dbaccount/api/create_db_account`.
        # Host-side that nginx is `localhost`; in-container it's `hmd_proxy`.
        #
        # It must carry the environment's route prefix — see ns_local_proxy().
        ns_local_proxy = self.ns_local_proxy()
        # In-container submit is opt-in: it requires a projectbuilder whose
        # `hmd-cli-deploy` understands the local endpoint (HMD_DEPLOYMENT_SERVICE_URL).
        # Older projectbuilder images would try the cloud API Gateway and fail the
        # node, so by default we DON'T pass the RID into the container and instead
        # submit produced Resources from the runner (see _submit_produced_resources).
        incontainer_submit = _is_truthy(
            os.environ.get("HMD_LOCAL_INCONTAINER_RESOURCE_SUBMIT")
        )

        # The Floci account this deploy targets. One Floci serves every account,
        # so the endpoint is the same for all of them and the *credentials* are
        # what select the account -- see `access_key_id` below. Getting that wrong
        # silently creates the environment's CDKTF resources in another account
        # rather than failing.
        from .floci_deployer import control_plane_target, env_target

        target = (
            env_target(self.env) if self.env is not None else control_plane_target()
        )
        floci_endpoint = os.environ.get(
            "FLOCI_WORKLOAD_ENDPOINT_DOCKER", target.internal_endpoint
        )

        # Resolve the repo path and any src/local overlay, then decide the
        # workspace to mount and the script to run.
        repo_path = self._repo_path(repo_class_name)
        overlay_dir = _overlay_dir_for(repo_path)
        workspace = repo_path
        tmp_workspace: Optional[str] = None
        deploy_script_overridden = False

        if overlay_dir is not None:
            if (overlay_dir / "deploy_local.sh").is_file():
                # Highest precedence: a full deploy-script override.
                logger.debug(
                    f"Using src/local/deploy_local.sh override for {repo_class_name}"
                )
                script = "bash src/local/deploy_local.sh"
                deploy_script_overridden = True
            elif _overlay_has_tool_files(overlay_dir):
                tmp_workspace = self._prepare_overlay_workspace(repo_path, overlay_dir)
                workspace = tmp_workspace

        # There is no bundled-in-image fallback for a repo's own deploy source
        # (unlike the best-effort sibling-repo mounts elsewhere in the local
        # platform) -- the projectbuilder image is a generic build toolchain,
        # not a per-repo artifact. Without a workspace the container falls
        # back to the image's default WORKDIR (`/`), and the deploy script's
        # relative paths (e.g. hmd-cli-cdktf's `os.chdir("src/cdktf")`) fail
        # with a confusing downstream FileNotFoundError instead of this.
        if not workspace:
            message = (
                f"Could not resolve a working tree for {repo_class_name}: no "
                f"bundled build artifact, no source.path declared in the "
                f"environment manifest, and $HMD_REPO_HOME/{repo_class_name} "
                f"was not found. Set HMD_REPO_HOME to a directory containing "
                f"this repo, or declare source.path for it in the environment "
                f"manifest."
            )
            logger.error(message)
            return _NodeResult(False, stderr=message)

        # A local NeuronSphere has no Artifact Librarian, so `hmd deploy` must take
        # its code from a local source instead of pulling the build bundle. Prefer a
        # previously-downloaded bundle when one is available for this repo
        # (HMD_LOCAL_DEPLOY_ARTIFACT_ROOT), otherwise deploy from the mounted source
        # (`--local`). Skip when a deploy_local.sh override owns the command.
        artifact_root_mount = self._resolve_artifact_bundle_dir(node)
        if not deploy_script_overridden:
            if artifact_root_mount is not None:
                logger.debug(
                    f"Deploying {repo_class_name} from local artifact bundle "
                    f"({artifact_root_mount})"
                )
            else:
                script = _localize_deploy_script(script)

        cmd = [
            "docker",
            "run",
            "--rm",
            # Override the projectbuilder ENTRYPOINT (`hmd`) so the deploy script
            # runs under bash rather than being parsed as an `hmd` subcommand.
            "--entrypoint",
            "bash",
            "--network",
            DOCKER_NETWORK_NAME,
            "-e",
            f"AWS_ENDPOINT_URL={floci_endpoint}",
            # The account selector: Floci reads the account id straight off a
            # 12-digit access key. An ambient $AWS_ACCESS_KEY_ID would put every
            # environment's CDKTF state in the same account.
            "-e",
            f"AWS_ACCESS_KEY_ID={target.access_key_id}",
            "-e",
            f"AWS_SECRET_ACCESS_KEY={os.environ.get('AWS_SECRET_ACCESS_KEY', 'dummykey')}",
            "-e",
            f"AWS_DEFAULT_REGION={os.environ.get('AWS_REGION', 'us-west-2')}",
            "-e",
            "HMD_ENVIRONMENT=local",
            # hmd-cli-* asserts HMD_HOME is set; point it at a writable in-container
            # path (the deploy only needs scratch/cache space there).
            "-e",
            "HMD_HOME=/root/hmd",
            # `hmd cdktf deploy` unconditionally resolves docker registry
            # credentials (get_credentials reads DOCKER_USERNAME/DOCKER_PASSWORD).
            # Locally these feed only a no-op cdktf overlay, so dummy values satisfy
            # the pre-flight without configuring a real registry.
            "-e",
            f"DOCKER_USERNAME={os.environ.get('DOCKER_USERNAME', 'local')}",
            "-e",
            f"DOCKER_PASSWORD={os.environ.get('DOCKER_PASSWORD', 'local')}",
            "-e",
            f"HMD_DEPLOYMENT_SERVICE_URL={deployment_service_url}",
            "-e",
            f"NS_LOCAL_PROXY={ns_local_proxy}",
            # Scoped k3s cluster/container name so hmd-cli-helm's in-container
            # `_import_images_into_k3s` (`_k3s_container_name()`) targets THIS
            # HMD_HOME's `floci-eks-<cluster>` node, not the unscoped default.
            "-e",
            f"HMD_LOCAL_K3S_CLUSTER_NAME={self.cluster_name or K3S_CLUSTER_NAME}",
            "-e",
            f"HMD_CUSTOMER_CODE={os.environ.get('HMD_CUSTOMER_CODE', 'none')}",
            "-e",
            f"HMD_DID={self.env.deployment_id if self.env else os.environ.get('HMD_DID', 'aaa')}",
            "-e",
            f"HMD_REGION={os.environ.get('HMD_REGION', 'reg1')}",
            "-e",
            f"HMD_HOSTNAME={os.environ.get('HMD_HOSTNAME', 'localhost')}",
            "-v",
            "/var/run/docker.sock:/var/run/docker.sock",
        ]

        # Make the local k3s cluster reachable to `hmd helm --local` inside the
        # container. Best-effort: only mount if the kubeconfig exists.
        kubeconfig = self._kubeconfig_for_container()
        if kubeconfig is not None:
            cmd.extend(
                [
                    "-v",
                    f"{kubeconfig}:/root/.kube/config:ro",
                    "-e",
                    "HMD_LOCAL_K3S_KUBECONFIG=/root/.kube/config",
                ]
            )

        # Opt-in only: let the in-container `hmd deploy` submit produced Resources
        # itself (requires a local-aware projectbuilder). Otherwise the runner
        # submits them after the node succeeds (_submit_produced_resources).
        if incontainer_submit and rid_nid:
            cmd.extend(["-e", f"HMD_REPO_INSTANCE_DEPLOYMENT_ID={rid_nid}"])

        # Secondary source: mount the local artifact-bundle dir and point
        # hmd-cli-deploy at it (HMD_ARTIFACT_ROOT). It unzips <repo>_<ver>_build.zip
        # from here instead of pulling from the (absent) Artifact Librarian.
        if artifact_root_mount is not None and not deploy_script_overridden:
            cmd.extend(
                [
                    "-v",
                    f"{artifact_root_mount}:/artifacts:ro",
                    "-e",
                    "HMD_ARTIFACT_ROOT=/artifacts",
                ]
            )

        # Mount the (possibly overlaid) workspace.
        if workspace:
            cmd.extend(["-v", f"{workspace}:/workspace", "-w", "/workspace"])

        # Pass the deploy script as a mounted file rather than `bash -c <script>`.
        # A node with many resolved dependencies (e.g. trino -> metastore +
        # clickhouse + graph-db + users + ...) generates a script whose inlined
        # config exceeds ARG_MAX, so `bash -c <script>` fails before it runs with
        # "exec /bin/bash: argument list too long". The projectbuilder ENTRYPOINT is
        # already overridden to bash above, and the working dir is /workspace, so the
        # script's relative paths (./src/helm etc.) still resolve.
        script_file = tempfile.NamedTemporaryFile(
            "w", suffix=".sh", prefix="hmd-deploy-", delete=False
        )
        script_file.write(script)
        script_file.close()
        cmd.extend(
            [
                "-v",
                f"{script_file.name}:/tmp/hmd-deploy-node.sh:ro",
                image,
                "/tmp/hmd-deploy-node.sh",
            ]
        )

        logger.debug(f"Running projectbuilder for {node['instance_name']}")
        resource_count = 0
        try:
            result = subprocess.run(cmd, capture_output=True, text=True)
            # Submit produced Resources from the runner while the (possibly
            # temp) workspace still exists — hmd-cli-helm renders them under
            # meta-data/resources_output/ during the deploy. Skipped when the
            # in-container path already handled submission, and on a destroy,
            # which tears Resources down rather than producing them (any
            # resources_output/ left over from the prior deploy would otherwise
            # be re-submitted for an instance that no longer exists).
            if result.returncode == 0 and not incontainer_submit and not destroy:
                resource_count = self._submit_produced_resources(workspace, node)
        finally:
            os.unlink(script_file.name)
            if tmp_workspace is not None:
                shutil.rmtree(os.path.dirname(tmp_workspace), ignore_errors=True)

        if result.returncode != 0:
            logger.error(
                f"Projectbuilder failed for {node['instance_name']}: "
                f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
            )
        else:
            logger.debug(f"Projectbuilder succeeded for {node['instance_name']}")

        return _NodeResult(
            success=result.returncode == 0,
            resource_count=resource_count,
            returncode=result.returncode,
            stdout=result.stdout,
            stderr=result.stderr,
        )

    @staticmethod
    def _resolve_artifact_bundle_dir(node: Dict) -> Optional[str]:
        """Return the host artifact-bundle dir for a node, if bundle mode applies.

        Bundle (secondary) source: when ``HMD_LOCAL_DEPLOY_ARTIFACT_ROOT`` points at a
        directory containing this repo's ``<repo>_<ver>_build.zip`` (the name
        hmd-cli-deploy's ``--artifact-root`` / ``HMD_ARTIFACT_ROOT`` branch expects),
        return that directory so the caller mounts it and sets ``HMD_ARTIFACT_ROOT``.
        Returns ``None`` (→ mounted-source primary) when unset or the bundle is absent.
        """
        root = os.environ.get("HMD_LOCAL_DEPLOY_ARTIFACT_ROOT")
        if not root or not os.path.isdir(root):
            return None
        repo = node.get("repo_class_name", "")
        version = node.get("repo_class_version")
        if not version:
            repo_home = os.environ.get("HMD_REPO_HOME", "")
            try:
                with open(os.path.join(repo_home, repo, "meta-data", "VERSION")) as f:
                    version = f.read().strip()
            except OSError:
                return None
        bundle = os.path.join(root, f"{repo}_{version}_build.zip")
        return root if os.path.isfile(bundle) else None

    def _submit_produced_resources(self, workspace: Optional[str], node: Dict) -> int:
        """Submit Resources the deploy rendered under meta-data/resources_output/.

        NERD0006: hmd-cli-helm writes one JSON per produced Resource (plus a
        legacy single ``resources_output.json`` list) into the mounted workspace.
        The runner reads them and POSTs to the local Deployment Service against the
        node's RepoInstanceDeployment id — the local-mode equivalent of
        ``hmd deploy``'s ``submit_resources``, without needing a projectbuilder
        that can reach the service. Best-effort.

        :returns: The number of Resources submitted.
        """
        import glob

        rid_nid = node.get("rid_nid")
        if not workspace or not rid_nid:
            return 0

        meta_dir = os.path.join(workspace, "meta-data")
        resources: List[Dict] = []
        for path in sorted(
            glob.glob(os.path.join(meta_dir, "resources_output", "*.json"))
        ):
            try:
                with open(path) as f:
                    doc = json.load(f)
                resources.extend(doc if isinstance(doc, list) else [doc])
            except (OSError, json.JSONDecodeError):
                pass
        legacy = os.path.join(meta_dir, "resources_output.json")
        if os.path.isfile(legacy):
            try:
                with open(legacy) as f:
                    doc = json.load(f)
                resources.extend(doc if isinstance(doc, list) else [doc])
            except (OSError, json.JSONDecodeError):
                pass

        if not resources:
            return 0
        # Buffer the *payload*, never the workspace: the overlay workspace is a
        # temp dir the caller deletes as soon as the node finishes, so a deferred
        # replay would have nothing left to read.
        self._post_resources(rid_nid, resources, node["instance_name"])
        return len(resources)

    def _post_resources(
        self, rid_nid: str, resources: List[Dict], instance_name: str
    ) -> bool:
        """POST produced Resources, or buffer them when tracking is off."""
        if not self.tracking:
            self._deferred.append(
                ("_post_resources", (rid_nid, resources, instance_name))
            )
            return False
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/submit_resources",
                json={
                    "repo_instance_deployment_id": rid_nid,
                    "resources": resources,
                },
                timeout=30,
            )
            resp.raise_for_status()
            logger.debug(
                f"Tracked {len(resources)} produced resource(s) for {instance_name}"
            )
            return True
        except requests.RequestException as e:
            self._log_tracking_failure(
                f"submit produced resources for {instance_name}", e
            )
            return False

    def _local_kubeconfig_path(self) -> Optional[str]:
        """Resolve the k3s kubeconfig, mirroring hmd-cli-helm's lookup.

        The environment's own kubeconfig wins: every environment has its own
        cluster, so an ambient ``KUBECONFIG`` may well point at a different one.
        """
        candidates = [
            str(self.env.kubeconfig) if self.env is not None else None,
            os.environ.get("HMD_LOCAL_K3S_KUBECONFIG"),
            os.environ.get("KUBECONFIG"),
        ]
        hmd_home = os.environ.get("HMD_HOME")
        if hmd_home:
            candidates.append(os.path.join(hmd_home, ".cache", "k3s", "kubeconfig"))
        for c in candidates:
            if c and os.path.isfile(c):
                return c
        return None

    def _kubeconfig_for_container(self) -> Optional[str]:
        """Resolve a kubeconfig usable from *inside* the projectbuilder container.

        The mounted kubeconfig's ``server`` is a host-published port
        (``https://localhost:<port>``, written by ``write_kubeconfig`` for host-side
        ``kubectl`` use) -- unreachable from inside a container on the
        ``neuronsphere_default`` network. Rewrites it to the in-network Floci EKS
        alias (``https://floci-eks-<cluster>:6443``), mirroring hmd-cli-helm's
        ``_kubeconfig_with_server``. Unlike that helper (which only substitutes the
        endpoint when a deploying repo's manifest happens to declare a
        ``kubernetes-cluster`` resource dependency, per NERD0006), this applies
        unconditionally to every node the runner executes, since the container is
        always on that network regardless of the target repo's dependencies.
        Falls back to the raw kubeconfig path if no cluster name is known or the
        file can't be parsed.
        """
        path = self._local_kubeconfig_path()
        if path is None or not self.cluster_name:
            return path
        try:
            with open(path) as f:
                cfg = yaml.safe_load(f)
            for entry in cfg.get("clusters", []):
                cluster = entry.setdefault("cluster", {})
                cluster["server"] = f"https://floci-eks-{self.cluster_name}:6443"
                cluster["insecure-skip-tls-verify"] = True
                cluster.pop("certificate-authority-data", None)
                cluster.pop("certificate-authority", None)
            tmp = tempfile.NamedTemporaryFile(
                "w", prefix="hmd-workflow-", suffix="-kubeconfig.yaml", delete=False
            )
            yaml.safe_dump(cfg, tmp)
            tmp.close()
            return tmp.name
        except (OSError, yaml.YAMLError, AttributeError) as e:
            logger.warning(f"Could not rewrite kubeconfig for in-container use: {e}")
            return path

    def replay_into(self, base_url: str) -> int:
        """Flush everything buffered while ``tracking`` was off.

        Ordering is preserved because a Resource submission is keyed by the
        RepoInstanceDeployment its status update settles.

        .. note::

           Bootstrap-DAG nodes currently carry **locally generated** ids
           (``bootstrap_dag._rid``), which no ms-deployment entity corresponds
           to, so replaying their statuses returns 404 and records nothing.
           Recording the control-plane bring-up in the graph needs those
           entities created first -- a control-plane BOM seeded and applied the
           way an environment's is -- which is not done yet. The 404s are logged
           at debug rather than error for that reason, and this returns how many
           calls actually *landed* so a caller cannot report success that did
           not happen.

        :returns: The number of deferred calls that succeeded.
        """
        self.base_url = base_url
        self.tracking = True
        self._replaying = True
        deferred, self._deferred = self._deferred, []
        succeeded = 0
        try:
            for method, args in deferred:
                if getattr(self, method)(*args):
                    succeeded += 1
        finally:
            self._replaying = False
        if deferred:
            logger.debug(
                f"Replayed {succeeded}/{len(deferred)} deferred call(s) into {base_url}"
            )
        return succeeded

    def _set_status(self, rid_nid: str, status: str) -> bool:
        """Update a RepoInstanceDeployment status. True if it landed."""
        if not self.tracking:
            self._deferred.append(("_set_status", (rid_nid, status)))
            return False
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_deployment_status/{rid_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
            return True
        except requests.RequestException as e:
            self._log_tracking_failure(f"set RID status {rid_nid} to {status}", e)
            return False

    def _set_csd_status(self, csd_nid: str, status: str) -> bool:
        """Update a ChangeSetDeployment status. True if it landed."""
        if not self.tracking:
            self._deferred.append(("_set_csd_status", (csd_nid, status)))
            return False
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_change_set_deployment_status/{csd_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
            return True
        except requests.RequestException as e:
            self._log_tracking_failure(f"set CSD status {csd_nid} to {status}", e)
            return False

    def _log_tracking_failure(self, what: str, e: Exception) -> None:
        """Report a failed status/Resource call at the right volume.

        A 404 while replaying is the known gap described in :meth:`replay_into`
        -- the entity was never registered -- not a failure of this run, and
        eight of them at ERROR read like the bootstrap broke when it did not.
        """
        status = getattr(getattr(e, "response", None), "status_code", None)
        if self._replaying and status == 404:
            logger.debug(f"Could not {what}: no such entity (not registered)")
        else:
            logger.error(f"Failed to {what}: {e}")
