"""LocalWorkflowRunner for executing deployment DAGs locally.

Replaces Argo workflow execution in local extend mode. For each node
in the deployment manifest (generated by ms-deployment), the runner
resolves the repo's deploy strategy and either skips the node or runs
the deploy script in an hmd-img-projectbuilder container against the
single Floci instance.

Strategy resolution is 3-tier:
1. Per-repo ``src/local/nsplugin.json`` ``local_deploy.strategy``
2. Central ``local_overrides.json`` (fallback)
3. Default: ``"default"`` — attempt execution in projectbuilder
"""

import json
import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, List, Optional

import requests
from cement import minimal_logger

logger = minimal_logger("local_workflow_runner")

# Strategies that skip execution and mark DEPLOYED immediately
SKIP_STRATEGIES = {"skip", "local_storage"}

# Directories that are never worth copying into an overlay workspace (build
# output, VCS metadata, dependency caches). Keeps the temp copy small/fast.
_OVERLAY_COPY_IGNORE = shutil.ignore_patterns(
    ".git",
    "node_modules",
    "build",
    "target",
    "dist",
    "cdktf.out",
    ".terraform",
    "__pycache__",
    "*.egg-info",
)


def _is_truthy(value: Optional[str]) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def _repo_path_for(repo_class_name: str) -> Optional[str]:
    """Return the HMD_REPO_HOME path for a repo class, if it exists locally."""
    repo_home = os.environ.get("HMD_REPO_HOME", "")
    if not repo_home or not repo_class_name:
        return None
    candidate = os.path.join(repo_home, repo_class_name)
    return candidate if os.path.isdir(candidate) else None


def _overlay_dir_for(repo_path: Optional[str]) -> Optional[Path]:
    """Return the ``src/local`` overlay directory for a repo path, if present.

    A repo may ship Floci-safe alternates under ``src/local`` that overlay its
    real deploy sources at local-deploy time:

      src/local/deploy_local.sh    full deploy-script override (highest priority)
      src/local/cdktf/             alternate CdkTf stack, overlays src/cdktf/
      src/local/helm/              alternate helm chart/values, overlays src/helm/
      src/local/config_local.json  overlays meta-data/config_local.json
    """
    if not repo_path:
        return None
    overlay = Path(repo_path) / "src" / "local"
    return overlay if overlay.is_dir() else None


def _overlay_has_tool_files(overlay_dir: Path) -> bool:
    """True if the overlay contains cdktf/helm/config alternates to apply."""
    return (
        (overlay_dir / "cdktf").is_dir()
        or (overlay_dir / "helm").is_dir()
        or (overlay_dir / "config_local.json").is_file()
    )


def _load_local_deploy_strategy(repo_class_name: str) -> Optional[str]:
    """Load the local_deploy.strategy from a repo's src/local/nsplugin.json.

    :param repo_class_name: The repo directory name (e.g., "hmd-vpc")
    :returns: The strategy string ("skip", "default", etc.) or None if not found
    """
    repo_home = os.environ.get("HMD_REPO_HOME", "")
    if not repo_home:
        return None

    nsplugin_path = (
        Path(repo_home) / repo_class_name / "src" / "local" / "nsplugin.json"
    )
    if not nsplugin_path.exists():
        return None

    try:
        with open(nsplugin_path) as f:
            config = json.load(f)
        return config.get("local_deploy", {}).get("strategy")
    except (json.JSONDecodeError, KeyError):
        return None


class LocalWorkflowRunner:
    """Execute deployment DAG nodes locally using Docker containers.

    Strategy handlers:
    - "skip": Mark DEPLOYED without executing (cloud-only infrastructure)
    - "local_storage": Mark DEPLOYED (storage provisioner handled it)
    - "compose_substitute": Mark DEPLOYED (compose container already started)
    - "default" / None: Run the real deploy script in projectbuilder against the
      single Floci, applying any ``src/local`` Floci-safe overlay for the repo.
    - "src_local": Same real deploy, but the repo MUST ship a ``src/local``
      overlay; if it doesn't, fall back to marking DEPLOYED with a warning
      (the real deploy would call Floci-unsupported APIs).
    """

    def __init__(self, base_url: str, overrides: Dict = None):
        """
        :param base_url: ms-deployment base URL (e.g., http://localhost/hmd_ms_deployment)
        :param overrides: Central local_overrides.json dict (fallback for repos without nsplugin.json)
        """
        self.base_url = base_url
        self.overrides = overrides or {}

    def _resolve_strategy(self, repo_class_name: str) -> str:
        """Resolve the deploy strategy for a repo class (3-tier lookup).

        1. Per-repo src/local/nsplugin.json local_deploy.strategy
        2. Central local_overrides.json
        3. Default: "default"
        """
        # Tier 1: per-repo nsplugin.json
        strategy = _load_local_deploy_strategy(repo_class_name)
        if strategy is not None:
            return strategy

        # Tier 2: central overrides
        if repo_class_name in self.overrides:
            strategy = self.overrides[repo_class_name].get("strategy")
            if strategy is not None:
                return strategy

        # Tier 3: default — attempt execution in projectbuilder
        return "default"

    def run(self, csd_nid: str, nodes: List[Dict]) -> bool:
        """Execute deployment nodes in DAG order.

        :param csd_nid: The ChangeSetDeployment identifier
        :param nodes: Ordered list of node descriptors from generate_local_deployment
        :returns: True if all nodes succeeded
        """
        self._set_csd_status(csd_nid, "STARTED")

        # Log strategy summary
        strategy_counts: Dict[str, int] = {}
        for node in nodes:
            s = self._resolve_strategy(node["repo_class_name"])
            strategy_counts[s] = strategy_counts.get(s, 0) + 1
        summary = ", ".join(f"{k}: {v}" for k, v in sorted(strategy_counts.items()))
        logger.info(f"Strategy summary: {summary}")
        print(f"  Strategy summary: {summary}")

        for node in nodes:
            instance_name = node["instance_name"]
            repo_class_name = node["repo_class_name"]
            rid_nid = node["rid_nid"]
            strategy = self._resolve_strategy(repo_class_name)

            if strategy in SKIP_STRATEGIES:
                logger.info(f"SKIP: {instance_name} ({repo_class_name}) [{strategy}]")
                print(f"  SKIP: {instance_name} ({repo_class_name})")
                self._set_status(rid_nid, "DEPLOYED")
                continue

            if strategy == "compose_substitute":
                logger.info(
                    f"COMPOSE: {instance_name} ({repo_class_name}) — container already started"
                )
                print(f"  COMPOSE: {instance_name} ({repo_class_name})")
                self._set_status(rid_nid, "DEPLOYED")
                continue

            # "src_local" requires a Floci-safe overlay; without one the real
            # deploy would call unsupported APIs, so mark DEPLOYED and move on.
            if (
                strategy == "src_local"
                and _overlay_dir_for(_repo_path_for(repo_class_name)) is None
            ):
                logger.warning(
                    f"src_local strategy for {repo_class_name} but no src/local "
                    f"overlay found — marking DEPLOYED without executing."
                )
                print(f"  SKIP (no overlay): {instance_name} ({repo_class_name})")
                self._set_status(rid_nid, "DEPLOYED")
                continue

            # strategy == "default"/"src_local"/anything else: execute in projectbuilder
            logger.info(f"DEPLOY: {instance_name} ({repo_class_name})")
            print(f"  DEPLOY: {instance_name} ({repo_class_name})")

            success = self._execute_in_projectbuilder(node)
            if success:
                self._set_status(rid_nid, "DEPLOYED")
            else:
                self._set_status(rid_nid, "FAILED")
                self._set_csd_status(csd_nid, "FAILED")
                logger.error(f"FAILED: {instance_name} ({repo_class_name})")
                print(f"  FAILED: {instance_name}")
                return False

        self._set_csd_status(csd_nid, "COMPLETED")
        return True

    def _prepare_overlay_workspace(self, repo_path: str, overlay_dir: Path) -> str:
        """Copy the repo to a temp dir and overlay its src/local alternates.

        Copies the repo (minus heavy/irrelevant dirs) so the developer's tree is
        never mutated, then overlays Floci-safe alternates on top:
          src/local/cdktf/*           -> src/cdktf/
          src/local/helm/*            -> src/helm/
          src/local/config_local.json -> meta-data/config_local.json

        :returns: Path to the prepared temp workspace (caller must clean it up)
        """
        tmp_root = tempfile.mkdtemp(prefix="ns-overlay-")
        workspace = os.path.join(tmp_root, os.path.basename(repo_path.rstrip("/")))
        shutil.copytree(repo_path, workspace, ignore=_OVERLAY_COPY_IGNORE)

        applied: List[str] = []
        for tool in ("cdktf", "helm"):
            src = overlay_dir / tool
            if src.is_dir():
                dest = Path(workspace) / "src" / tool
                dest.mkdir(parents=True, exist_ok=True)
                shutil.copytree(src, dest, dirs_exist_ok=True)
                applied.append(f"src/local/{tool} -> src/{tool}")

        cfg = overlay_dir / "config_local.json"
        if cfg.is_file():
            dest = Path(workspace) / "meta-data" / "config_local.json"
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(cfg, dest)
            applied.append("src/local/config_local.json -> meta-data/config_local.json")

        if applied:
            logger.info(f"Applied src/local overlay: {', '.join(applied)}")
        return workspace

    def _execute_in_projectbuilder(self, node: Dict) -> bool:
        """Run a deploy script in an hmd-img-projectbuilder container.

        The container runs on the neuronsphere_default network with
        AWS_ENDPOINT_URL pointing to the single Floci instance so CDKTF and
        other AWS tools target the local emulator. If the repo ships a
        ``src/local`` overlay, its Floci-safe alternates are applied first:
        a ``deploy_local.sh`` fully replaces the generated node script, and
        ``cdktf``/``helm``/``config_local.json`` overlay the real deploy sources
        in an isolated temp workspace (the developer's tree is never mutated).
        """
        registry = os.environ.get(
            "HMD_LOCAL_NS_CONTAINER_REGISTRY", "ghcr.io/neuronsphere"
        )
        pb_version = os.environ.get("HMD_PROJECTBUILDER_VERSION", "stable")
        image = f"{registry}/hmd-img-projectbuilder:{pb_version}"

        script = node.get("script", "")
        if not script:
            logger.warning(f"No script for node {node['instance_name']}, skipping")
            return True

        repo_class_name = node["repo_class_name"]

        # NERD0004/0006: expose a container-reachable Deployment Service URL so a
        # projectbuilder carrying a local-aware `hmd deploy` can post produced
        # Resources back itself. `self.base_url` uses `localhost`, which isn't
        # reachable inside the container — translate it to the `neuronsphere`
        # docker-network alias (overridable).
        rid_nid = node.get("rid_nid", "")
        deployment_service_url = os.environ.get(
            "HMD_DEPLOYMENT_SERVICE_URL",
            self.base_url.replace("localhost", "neuronsphere").replace(
                "127.0.0.1", "neuronsphere"
            ),
        )
        # In-container submit is opt-in: it requires a projectbuilder whose
        # `hmd-cli-deploy` understands the local endpoint (HMD_DEPLOYMENT_SERVICE_URL).
        # Older projectbuilder images would try the cloud API Gateway and fail the
        # node, so by default we DON'T pass the RID into the container and instead
        # submit produced Resources from the runner (see _submit_produced_resources).
        incontainer_submit = _is_truthy(
            os.environ.get("HMD_LOCAL_INCONTAINER_RESOURCE_SUBMIT")
        )

        # Single Floci endpoint (control plane == workload account); resolved
        # via the `neuronsphere` Docker network alias. FLOCI_WORKLOAD_ENDPOINT_DOCKER
        # is still honored for backward compatibility but now points here too.
        floci_endpoint = os.environ.get(
            "FLOCI_WORKLOAD_ENDPOINT_DOCKER", "http://neuronsphere:4566"
        )

        # Resolve the repo path and any src/local overlay, then decide the
        # workspace to mount and the script to run.
        repo_path = _repo_path_for(repo_class_name)
        overlay_dir = _overlay_dir_for(repo_path)
        workspace = repo_path
        tmp_workspace: Optional[str] = None

        if overlay_dir is not None:
            if (overlay_dir / "deploy_local.sh").is_file():
                # Highest precedence: a full deploy-script override.
                logger.info(
                    f"Using src/local/deploy_local.sh override for {repo_class_name}"
                )
                script = "bash src/local/deploy_local.sh"
            elif _overlay_has_tool_files(overlay_dir):
                tmp_workspace = self._prepare_overlay_workspace(repo_path, overlay_dir)
                workspace = tmp_workspace

        cmd = [
            "docker",
            "run",
            "--rm",
            # Override the projectbuilder ENTRYPOINT (`hmd`) so the deploy script
            # runs under bash rather than being parsed as an `hmd` subcommand.
            "--entrypoint",
            "bash",
            "--network",
            "neuronsphere_default",
            "-e",
            f"AWS_ENDPOINT_URL={floci_endpoint}",
            "-e",
            f"AWS_ACCESS_KEY_ID={os.environ.get('AWS_ACCESS_KEY_ID', 'dummykey')}",
            "-e",
            f"AWS_SECRET_ACCESS_KEY={os.environ.get('AWS_SECRET_ACCESS_KEY', 'dummykey')}",
            "-e",
            f"AWS_DEFAULT_REGION={os.environ.get('AWS_REGION', 'us-west-2')}",
            "-e",
            "HMD_ENVIRONMENT=local",
            # hmd-cli-* asserts HMD_HOME is set; point it at a writable in-container
            # path (the deploy only needs scratch/cache space there).
            "-e",
            "HMD_HOME=/root/hmd",
            "-e",
            f"HMD_DEPLOYMENT_SERVICE_URL={deployment_service_url}",
            "-e",
            f"HMD_CUSTOMER_CODE={os.environ.get('HMD_CUSTOMER_CODE', 'none')}",
            "-e",
            f"HMD_DID={os.environ.get('HMD_DID', 'aaa')}",
            "-e",
            f"HMD_REGION={os.environ.get('HMD_REGION', 'reg1')}",
            "-e",
            f"HMD_HOSTNAME={os.environ.get('HMD_HOSTNAME', 'localhost')}",
            "-v",
            "/var/run/docker.sock:/var/run/docker.sock",
        ]

        # Make the local k3s cluster reachable to `hmd helm --local` inside the
        # container. Best-effort: only mount if the kubeconfig exists.
        kubeconfig = self._local_kubeconfig_path()
        if kubeconfig is not None:
            cmd.extend(
                [
                    "-v",
                    f"{kubeconfig}:/root/.kube/config:ro",
                    "-e",
                    "HMD_LOCAL_K3S_KUBECONFIG=/root/.kube/config",
                ]
            )

        # Opt-in only: let the in-container `hmd deploy` submit produced Resources
        # itself (requires a local-aware projectbuilder). Otherwise the runner
        # submits them after the node succeeds (_submit_produced_resources).
        if incontainer_submit and rid_nid:
            cmd.extend(["-e", f"HMD_REPO_INSTANCE_DEPLOYMENT_ID={rid_nid}"])

        # Mount the (possibly overlaid) workspace.
        if workspace:
            cmd.extend(["-v", f"{workspace}:/workspace", "-w", "/workspace"])

        # The projectbuilder image's ENTRYPOINT is `hmd`, so the deploy script
        # must be run under an explicit bash entrypoint (otherwise the args land
        # as `hmd bash -c ...` -> "invalid choice: 'bash'").
        cmd.extend([image, "-c", script])

        logger.info(f"Running projectbuilder for {node['instance_name']}")
        try:
            result = subprocess.run(cmd, capture_output=True, text=True)
            # Submit produced Resources from the runner while the (possibly
            # temp) workspace still exists — hmd-cli-helm renders them under
            # meta-data/resources_output/ during the deploy. Skipped when the
            # in-container path already handled submission.
            if result.returncode == 0 and not incontainer_submit:
                self._submit_produced_resources(workspace, node)
        finally:
            if tmp_workspace is not None:
                shutil.rmtree(os.path.dirname(tmp_workspace), ignore_errors=True)

        if result.returncode != 0:
            logger.error(
                f"Projectbuilder failed for {node['instance_name']}: "
                f"exit={result.returncode}\nstdout={result.stdout}\nstderr={result.stderr}"
            )
        else:
            logger.info(f"Projectbuilder succeeded for {node['instance_name']}")

        return result.returncode == 0

    def _submit_produced_resources(self, workspace: Optional[str], node: Dict) -> int:
        """Submit Resources the deploy rendered under meta-data/resources_output/.

        NERD0006: hmd-cli-helm writes one JSON per produced Resource (plus a
        legacy single ``resources_output.json`` list) into the mounted workspace.
        The runner reads them and POSTs to the local Deployment Service against the
        node's RepoInstanceDeployment id — the local-mode equivalent of
        ``hmd deploy``'s ``submit_resources``, without needing a projectbuilder
        that can reach the service. Best-effort.

        :returns: The number of Resources submitted.
        """
        import glob

        rid_nid = node.get("rid_nid")
        if not workspace or not rid_nid:
            return 0

        meta_dir = os.path.join(workspace, "meta-data")
        resources: List[Dict] = []
        for path in sorted(
            glob.glob(os.path.join(meta_dir, "resources_output", "*.json"))
        ):
            try:
                with open(path) as f:
                    doc = json.load(f)
                resources.extend(doc if isinstance(doc, list) else [doc])
            except (OSError, json.JSONDecodeError):
                pass
        legacy = os.path.join(meta_dir, "resources_output.json")
        if os.path.isfile(legacy):
            try:
                with open(legacy) as f:
                    doc = json.load(f)
                resources.extend(doc if isinstance(doc, list) else [doc])
            except (OSError, json.JSONDecodeError):
                pass

        if not resources:
            return 0

        try:
            resp = requests.post(
                f"{self.base_url}/apiop/submit_resources",
                json={
                    "repo_instance_deployment_id": rid_nid,
                    "resources": resources,
                },
                timeout=30,
            )
            resp.raise_for_status()
            logger.info(
                f"Tracked {len(resources)} produced resource(s) for "
                f"{node['instance_name']}"
            )
            print(f"  Tracked {len(resources)} resource(s) for {node['instance_name']}")
            return len(resources)
        except requests.RequestException as e:
            logger.warning(
                f"Failed to submit produced resources for {node['instance_name']}: {e}"
            )
            return 0

    @staticmethod
    def _local_kubeconfig_path() -> Optional[str]:
        """Resolve the local k3s kubeconfig, mirroring hmd-cli-helm's lookup."""
        candidates = [
            os.environ.get("HMD_LOCAL_K3S_KUBECONFIG"),
            os.environ.get("KUBECONFIG"),
        ]
        hmd_home = os.environ.get("HMD_HOME")
        if hmd_home:
            candidates.append(os.path.join(hmd_home, ".cache", "k3s", "kubeconfig"))
        for c in candidates:
            if c and os.path.isfile(c):
                return c
        return None

    def _set_status(self, rid_nid: str, status: str):
        """Update a RepoInstanceDeployment status."""
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_deployment_status/{rid_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.error(f"Failed to set RID status {rid_nid} to {status}: {e}")

    def _set_csd_status(self, csd_nid: str, status: str):
        """Update a ChangeSetDeployment status."""
        try:
            resp = requests.post(
                f"{self.base_url}/apiop/set_change_set_deployment_status/{csd_nid}/{status}",
                timeout=30,
            )
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.error(f"Failed to set CSD status {csd_nid} to {status}: {e}")
